version: '3.4'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    volumes:
      - ltres_oltapi_data:/data/db
    ports:
      - 27017:27017
  
  rabbit:
    container_name: rabbit
    image: rabbitmq:3
    restart: always
    ports:
      - 5672:5672

  webapi:
    depends_on:
      - mongodb
    build: 
      context: .
      dockerfile: ./LTres.OltApi.WebApi/Dockerfile
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  workercontroller1:
    depends_on:
      - mongodb
      - rabbit
    build: 
      context: .
      dockerfile: ./LTres.OltApi.WorkerController/Dockerfile
      args:
        - VERSION=1.0.0.4

  # workercontroller2:
  #   depends_on:
  #     - mongodb
  #     - rabbit
  #   build: 
  #     context: .
  #     dockerfile: ./LTres.OltApi.WorkerController/Dockerfile

  worker1:
    depends_on:
      - rabbit
    build: 
      context: .
      dockerfile: ./LTres.OltApi.Worker/Dockerfile
      args:
        - VERSION=1.0.0.2
  
  # worker2:
  #   depends_on:
  #     - rabbit
  #   build: 
  #     context: .
  #     dockerfile: ./LTres.OltApi.Worker/Dockerfile

  # worker3:
  #   depends_on:
  #     - rabbit
  #   build: 
  #     context: .
  #     dockerfile: ./LTres.OltApi.Worker/Dockerfile

  # worker4:
  #   depends_on:
  #     - rabbit
  #   build: 
  #     context: .
  #     dockerfile: ./LTres.OltApi.Worker/Dockerfile

volumes:
  ltres_oltapi_data: